#!/usr/bin/env bash
set -euo pipefail

echo -e "\033[32mEjecutando chroot\033[0m"
source /etc/profile

emerge htop neovim
#export PS1="(chroot) ${PS1}"

systemctl preset-all # Preparar servicios base systemd

echo -e "\033[32mInstalando dependencias para el Kernel\033[0m"
echo ''
touch /etc/portage/package.use/kernel
echo "sys-kernel/gentoo-kernel-bin-6.6.74 initramfs" >> /etc/portage/package.use/kernel
echo ">=sys-kernel/installkernel-50 dracut" >> /etc/portage/package.use/kernel
echo "virtual/dist-kernel-6.6.74 dracut" >> /etc/portage/package.use/kernel

emerge dracut

echo -e "\033[32mInstalando Kernel\033[0m"
echo ''
emerge sys-kernel/gentoo-kernel-bin

echo -e "\033[32mInstalando grub\033[0m"
echo ''
emerge sys-boot/grub efibootmgr

grub-install --target=x86_64-efi --efi-directory=/boot/efi --removable --bootloader-id=Gentoo
grub-mkconfig -o /boot/grub/grub.cfg

emerge sys-kernel/gentoo-kernel-bin

grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=Gentoo --recheck
grub-mkconfig -o /boot/grub/grub.cfg

emerge net-misc/dhcpcd
systemctl enable dhcpcd

emerge sudo

echo -e "\033[32m===== Configurar zona horaria =====\033[0m"
ln -sf /usr/share/zoneinfo/America/Tegucigalpa /etc/localtime

echo -e "\033[32m===== Configurar hostname =====\033[0m"
echo "gentoo-pc" > /etc/hostname

echo -e "\033[32m===== Configurar contraseña de root =====\033[0m"
passwd

echo -e "\033[32m===== Crear usuario =====\033[0m"
read -rp "Nombre de Usuario: " usuario

useradd -m -G users,wheel,audio,video $usuario
echo -e "\033[32m===== Crear contraseña para $usuario =====\033[0m"
passwd "$usuario"

echo -e "\033[32m===== Editar sudoers =====\033[0m"
sed -ie 's/# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/g' /etc/sudoers

echo -e "\033[32m===== Asegurando datos en el disco =====\033[0m"
sync

rm -f /chroot

echo -e "\033[32m===== Proceso termina con exito =====\033[0m"
exit
